### CATCH ERROR
GET https://seg-server.vercel.app/api/booked
Content-Type: application/json

### GET ALL DATA
GET https://seg-server.vercel.app/api/booked
Content-Type: application/json

### GET A DATA BY ID
GET https://seg-server.vercel.app/api/booked/id/
Content-Type: application/json

### SAVE DATA
POST https://seg-server.vercel.app/api/booked
Content-Type: application/json

    

### UPDATE DATA
PATCH https://seg-server.vercel.app/api/booked
Content-Type: application/json

{
    ""name"": "A",
    "company": "A",
    "email": "A",
    "phone": 2000,
    "bookList": [
        
        {
        "book"Name"": "A",
        ""isbn"": "A",
        "price"": ""A",
        "qty": "A",
        "disc": "A"
    },
    {
        "book"Name"": "B",
        ""isbn"": "B",
        "price"": ""B",
        "qty": "B",
        "disc": "B"
    }
    ]
}

### DELETE DATA
DELETE https://seg-server.vercel.app/api/booked/id/
Content-Type: application/json